nn: 3000 # TODO: number of training data
num_exp: 5 # TODO: number of repeats
NUM_EPOCHES: 8000
batch_size: 512
p: 20
d: 20
m: 20
lr: 0.005
has_target_ReLU: True
has_target_predictor: False
alternative_optimization: False
rm_predictor: False
sigma0: 0
one_hot_latent: False
ws_noise_levels: (1, 1.25, 1.5, 2,) 
