nn: 3000 # number of training data
num_exp: 5 # number of repeats
NUM_EPOCHES: 8000
batch_size: 512
p: 20
d: 20
m: 20
lr: 0.005
has_online_ReLU: True
has_target_ReLU: True
alternative_optimization: True
rm_predictor: True
sigma0: 0
one_hot_latent: True
ws_noise: (None,)
masking_probs: (0.5)
