# some wandb specific experiment category

# Specify the broad type of experiment - e.g. augmentation_study
# Note: Keep this consistent for a specific category experiments
# exp_group: 'init-run-byol'
nn: 10000 # TODO: number of training data
num_exp: 20 # TODO: number of repeats
NUM_EPOCHES: 200
batch_size: 2000
p: 50
d: 10
m: 50
lr: 0.00001
has_target_ReLU: True
has_target_predictor: True
alternative_optimization: True
rm_predictor: False
sigma0: None
