nn: 3000 
num_exp: 5
NUM_EPOCHES: 8000
batch_size: 512
p: 50
d: 10
m: 50
lr: 0.005
has_online_ReLU: True
has_target_ReLU: True
has_target_predictor: False
alternative_optimization: True
rm_predictor: True
sigma0: 0
one_hot_latent: False
