# some wandb specific experiment category

# Specify the broad type of experiment - e.g. augmentation_study
# Note: Keep this consistent for a specific category experiments
# exp_group: 'init-run-byol'
nn: 5000 # TODO: number of training data
num_exp: 20 # TODO: number of repeats
NUM_EPOCHES: 400
batch_size: 500
p: 30
d: 10
m: 10
lr: 0.001
has_target_ReLU: True
has_target_predictor: True
alternative_optimization: True
rm_predictor: False
sigma0: None