# some wandb specific experiment category

# Specify the broad type of experiment - e.g. augmentation_study
# Note: Keep this consistent for a specific category experiments
# exp_group: 'init-run-byol'
nn: 5000 # TODO: number of training data
num_exp: 10 # TODO: number of repeats
NUM_EPOCHES: 100
batch_size: 500
p: 20
d: 10
m: 50
lr: 0.0001
has_online_ReLU: False
has_target_ReLU: False
sigma0: None